import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
// Design tokens transcribed verbatim from the Stitch "Clinical Utility System"
// design theme so the original markup classes resolve 1:1 in this app.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb59b',
        'tertiary-container': '#a33500',
        'surface-container': '#edeef0',
        'surface-container-highest': '#e1e2e4',
        background: '#f8f9fb',
        'surface-container-high': '#e7e8ea',
        'outline-variant': '#c3c6d6',
        'on-surface-variant': '#434654',
        'tertiary-fixed': '#ffdbcf',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f3f4f6',
        'secondary-fixed': '#afecff',
        'surface-tint': '#0c56d0',
        'surface-variant': '#e1e2e4',
        secondary: '#00687b',
        'secondary-container': '#50dcff',
        'success-green': '#36B37E',
        'inverse-on-surface': '#f0f1f3',
        outline: '#737685',
        'inverse-primary': '#b2c5ff',
        'on-error': '#ffffff',
        primary: '#003d9b',
        'on-secondary-fixed-variant': '#004e5d',
        'on-surface': '#191c1e',
        'primary-container': '#0052cc',
        'on-primary': '#ffffff',
        'warning-orange': '#FF8B00',
        surface: '#f8f9fb',
        'deep-navy': '#091E42',
        'text-main': '#172B4D',
        'on-background': '#191c1e',
        'on-secondary-container': '#005f71',
        'inverse-surface': '#2e3132',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#ffc6b2',
        'on-primary-fixed-variant': '#0040a2',
        'on-tertiary-fixed': '#380d00',
        'surface-dim': '#d9dadc',
        error: '#ba1a1a',
        'on-primary-container': '#c4d2ff',
        'text-subtle': '#6B778C',
        'surface-bright': '#f8f9fb',
        'primary-fixed': '#dae2ff',
        tertiary: '#7b2600',
        'on-secondary-fixed': '#001f27',
        'primary-fixed-dim': '#b2c5ff',
        'on-primary-fixed': '#001848',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#812800',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#48d7f9',
        // Dark-mode surfaces used by the mobile dark screen
        'dark-surface': '#0b1326',
        'dark-surface-container': '#171f33',
        'dark-surface-container-high': '#222a3d',
        'dark-on-surface': '#dae2fd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '32px',
        'container-max': '1200px',
        gutter: '24px',
        base: '8px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'price-display': ['Inter', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'price-display': ['24px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [forms],
}
